# -*- coding: utf-8 -*-
"""yolov10-cans2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9JFD-aZzb22L8trNFT14w2zPuBQWK5p

#YOLOv10 Object Detectiom on a Custom Dataset
"""

from google.colab import drive
drive.mount('/content/drive')

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

"""#Install YOLOv10"""

!pip install albumentations==1.4

!pip install -q supervision

!pip install -q git+https://github.com/THU-MIG/yolov10.git

"""#Download pre-trained weights"""

!mkdir -p {HOME}/weights
!wget -P {HOME}/weights -q https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10n.pt
!wget -P {HOME}/weights -q https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10s.pt
!wget -P {HOME}/weights -q https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10m.pt
!wget -P {HOME}/weights -q https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10b.pt
!wget -P {HOME}/weights -q https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10l.pt
!wget -P {HOME}/weights -q https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10x.pt
!ls -lh {HOME}/weights

"""#Inference with Pre-trained COCO Model"""

# Commented out IPython magic to ensure Python compatibility.
from IPython.desplay import Image

# %cd {HOME}

Image(filename='', height=600)

"""#Download dataset from Roboflow Universe"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="xeMAbLTVkHp84GqRx5wI")
project = rf.workspace("kayque-batista-de-oliveira").project("cup-95rwr")
version = project.version(1)
dataset = version.download("yolov8")

"""#Dataset
Copiar o dataset com suas respectivas pastas e imagens de teste para a raiz do colab
"""

# !cp -r /content/drive/MyDrive/Cans ./
!cp -r /content/drive/MyDrive/Can2 ./

"""#Custom Training"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

# !yolo task=detect mode=train epochs=50 batch=16 plots=True patience=8 val=True \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Cans/data.yaml

# 'train1'
# !yolo task=detect mode=train epochs=25 batch=8 plots=True imgsz = 640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640 name = 'train1' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train2'
# !yolo task=detect mode=train epochs=25 batch=8 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz800 name = 'train1' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train3'
# !yolo task=detect mode=train epochs=50 batch=8 plots=True imgsz = 640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640/epoc50 name = 'train1' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train3'
# !yolo task=detect mode=train epochs=100 batch=8 plots=True imgsz =    640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640/epoc100 name = 'train3' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train4'
# !yolo task=detect mode=train epochs=25 batch=16 plots=True imgsz =    640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640/batch16 name = 'train4' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train5'
# !yolo task=detect mode=train epochs=25 batch=32 plots=True imgsz =    640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640/batch32 name = 'train4' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train6'
# !yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz =   640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640/batch32/epoc100 name = 'train6' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train7'
!yolo task=detect mode=train epochs=200 batch=32 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.0 \
name = 'train8' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

!ls {HOME}/runs/detect/train/

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

# !yolo task=detect mode=train epochs=50 batch=16 plots=True patience=8 val=True \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Cans/data.yaml

# 'train1'
# !yolo task=detect mode=train epochs=25 batch=8 plots=True imgsz = 640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640 name = 'train1' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train2'
# !yolo task=detect mode=train epochs=25 batch=8 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz800 name = 'train1' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train3'
# !yolo task=detect mode=train epochs=50 batch=8 plots=True imgsz = 640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640/epoc50 name = 'train1' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train3'
# !yolo task=detect mode=train epochs=100 batch=8 plots=True imgsz =    640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640/epoc100 name = 'train3' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train4'
# !yolo task=detect mode=train epochs=25 batch=16 plots=True imgsz =    640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640/batch16 name = 'train4' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train5'
# !yolo task=detect mode=train epochs=25 batch=32 plots=True imgsz =    640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/imgsz640/batch32 name = 'train4' \
# model={HOME}/weights/yolov10n.pt \
# data={HOME}/Can2/data.yaml

# 'train6'
#!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz =   640 momentum = 0.937 verbose =  True dropout =  0.0 \
#project = {HOME}/yolov10small name = 'train8' \
#model={HOME}/weights/yolov10s.pt \
#data={HOME}/Can2/data.yaml


# 'train7'
#!yolo task=detect mode=train epochs=200 batch=32 plots=True imgsz = 640 momentum = 0.937 verbose =  True dropout =  0.0 \
#project = {HOME}/yolov10small name = 'train9' \
#model={HOME}/weights/yolov10s.pt \
#data={HOME}/Can2/data.yaml

#!cp -r /content/yolov10small /content/drive/MyDrive/ResultadosTCC/

# 'train10'
# !yolo task=detect mode=train epochs=100 batch=16 plots=True imgsz = 640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/yolov10medium name = 'train3' \
# model={HOME}/weights/yolov10m.pt \
# data={HOME}/Can2/data.yaml


# 'train11'
# !yolo task=detect mode=train epochs=200 batch=32 plots=True imgsz = 640 momentum = 0.937 verbose =  True dropout =  0.0 \
# project = {HOME}/yolov10low name = 'train11' \
# model={HOME}/weights/yolov10l.pt \
# data={HOME}/Can2/data.yaml


# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.5 verbose =  True dropout =  0.0 \
project = {HOME}/momentum name = 'train1' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.6 verbose =  True dropout =  0.0 \
project = {HOME}/momentum name = 'train2' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.7 verbose =  True dropout =  0.0 \
project = {HOME}/momentum name = 'train3' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.8 verbose =  True dropout =  0.0 \
project = {HOME}/momentum name = 'train4' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.9 verbose =  True dropout =  0.0 \
project = {HOME}/momentum name = 'train5' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

!cp -r /content/yolov10low/momentum /content/drive/MyDrive/ResultadosTCC/

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.2 \
project = {HOME}/dropout name = 'train1' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.25 \
project = {HOME}/dropout name = 'train2' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.3 \
project = {HOME}/dropout name = 'train3' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.35 \
project = {HOME}/dropout name = 'train4' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.4 \
project = {HOME}/dropout name = 'train5' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.45 \
project = {HOME}/dropout name = 'train6' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

# 'train10'
!yolo task=detect mode=train epochs=100 batch=32 plots=True imgsz = 800 momentum = 0.937 verbose =  True dropout =  0.5 \
project = {HOME}/dropout name = 'train7' \
model={HOME}/weights/yolov10s.pt \
data={HOME}/Can2/data.yaml

!cp -r /content/yolov10low/dropout /content/drive/MyDrive/ResultadosTCC/

!cp -r /content/runs/detect/train8 /content/drive/MyDrive/ResultadosTCC/

!cp -r /content/yolov10low/train716 /content/drive/MyDrive/ResultadosTCC/

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}')

import torch
print(torch.__version__)